# Rubocop configuration

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'pkg/**/*'

# Team preferences different from Rubocop defaults:
Style/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Style/ClassCheck:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/TrailingComma:
  EnforcedStyleForMultiline: comma

Style/FormatString:
  EnforcedStyle: sprintf

Style/Documentation:
  Exclude:
    - 'tests/**/*.rb'
